TK1_PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('login_register.urls')),
    path('', include('home.urls')),
    path('form/', include('form.urls')),
    path('info/', include('info.urls')),
    path('article/', include('article.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

form/urls.py
from django.urls import path

from . import views
from form.views import UserCreateView

app_name = 'form'

urlpatterns = [
    path('', UserCreateView.as_view(), name='form'),
    path('success/', views.success, name='success'),
]

info/urls.py
from django.urls import path
from . import views

app_name= 'info'

urlpatterns = [
    path('', views.index, name='info'),
    path('patient/', views.patient, name='patient'),
    path("details/<int:pk>", views.patient_details, name="patient_details"),
    path("delete/<int:pk>", views.delete_patient, name="delete_patient"),
    path('rumah_sakit/', views.daftar_rumah_sakit, name="daftar_rumah_sakit"),
]

info/models.py
from django.db import models

# Create your models here.
class KasusProvinsi(models.Model):
    provinsi = models.CharField(max_length=50)
    kasus_positif = models.IntegerField()
    kasus_sembuh = models.IntegerField()
    kasus_meninggal = models.IntegerField()

    def __str__(self):
        return self.provinsi

class RumahSakitRujukan(models.Model):
    rumah_sakit = models.CharField(max_length=100)
    alamat = models.CharField(max_length=500)
    region = models.CharField(max_length=500)
    nomor_telepon = models.CharField(max_length=100, blank=True, null=True)
    provinsi = models.CharField(max_length=200)

    def __str__(self):
        return self.rumah_sakit

info/views.py
import requests

from django.contrib import messages
from django.shortcuts import render, redirect

from form.models import Patient

from .models import KasusProvinsi, RumahSakitRujukan
from .helper import rumah_sakit_helper, kasus_provinsi_helper


def index(request):
    response = requests.get('https://api.kawalcorona.com/indonesia/provinsi')
    data = response.json()
    kasus_provinsi_helper(data)
    data_semua_kasus = KasusProvinsi.objects.all()
    return render(request, 'info/index.html', {
        "semua_data" : data_semua_kasus
    })

def patient(request):
    patients = Patient.objects.all()
    is_empty = False
    if not patients:
        is_empty = True
    context = {
        'patients': patients,
        'is_empty': is_empty,
    }
    return render(request, 'info/data.html', context)

def patient_details(request, pk):
    patient = Patient.objects.get(id=pk)
    context = {'patient': patient}
    return render(request, 'info/details.html', context)

def delete_patient(request, pk):
    if request.method == "POST":
        patient = Patient.objects.get(id=pk)
        patient.delete()
        messages.success(request, (f"{patient} deleted."))
    return redirect('info:patient')

def daftar_rumah_sakit(request):
    response = requests.get('https://dekontaminasi.com/api/id/covid19/hospitals')
    data = response.json()
    rumah_sakit_helper(data)
    daftar_semua_rumah_sakit = RumahSakitRujukan.objects.all()
    return render(request, "info/rumah_sakit.html", {
        "rumah_sakit_rujukan": daftar_semua_rumah_sakit
    })

info/templates/info/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    {% block css_tambahan %}{% endblock css_tambahan %}
    <link rel="shortcut icon" href="{% static 'home/images/icons8_virus_48_xbi_icon.ico' %}">
    <title>Form Corona - {% block title %}{% endblock title %}</title>
    <style>
        html {
            font-family: "Roboto", sans-serif;
        }
    </style>
    <script>
        window.onscroll = () => {
                if (window.innerHeight + window.scrollY >= document.querySelector('#example').offsetHeight) {
                    document.querySelector('.navbar').style.background = '#00ac96';
                } else {
                    document.querySelector('.navbar').style.background = 'transparent';
                }
            }
    </script>
</head>
<body>

    <!-- Header -->
    {% block header %}
    {% endblock  %}


    {% block content %}
    {% endblock content %}


    <!-- Footer -->
    {% include "home/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>


    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <!-- Source: https://datatables.net/examples/styling/bootstrap4 -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
                $('#example').DataTable({
                });
            });
    </script>
</body>
</html>

info/templates/info/data.html
{% extends 'info/base.html' %}
{% load static %}
{% block title %}Patient Data{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

{% block content %}
    <div class="container my-4">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center info my-5 py-4">
                <h1 class="font-weight-bold header">List of Patients Registered</h1>
                <hr>
            </div>
        </div>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

        {% for patient in patients %}
            <div class="card mt-3">
                <div class="card-body d-flex justify-content-between flex-column flex-md-row">
                    <div>
                        <a href="{% url 'info:patient_details' patient.id %}">
                            <h5 class="card-title">{{ patient.name }}</h5>
                        </a>
                        <h6 class="card-subtitle mb-2 text-muted">{{ patient.age }} ({{ patient.sex }})</h6>
                    </div>
                    <form action="{% url 'info:delete_patient' patient.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger card-link mt-2 mr-md-4 align-self-center" type="input">
                            DELETE
                        </button>
                    </form>    
                </div>
            </div>
        {% endfor %}

        {% if is_empty %}
            <div class="container d-flex h-100">
                <div class="row align-self-center w-100">
                <div class="col-lg-4 col-md-6 col-sm-6 mx-auto">
                    <div class="container" align="center">
                        <h3>Patient Empty</h3>
                        <p class="lead">Add a patient and it will show up here.</p>
                    </div>
                </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

info/templates/info/details.html
{% extends 'info/base.html' %}
{% load static %}
{% block title %}Patient Details{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-lg-8 text-center info my-5 py-4">
            <h1 class="font-weight-bold header">Patient Details</h1>
            <hr>
        </div>
    </div>
    <div class="jumbotron">
        <h1 class="display-4">{{ patient.name }}</h1>
        <table class="table w-auto">
            <tbody>
                <tr>
                    <th>Age</th>
                    <td><span class="badge badge-light">{{ patient.age }}</span></td>
                </tr>
                <tr>
                    <th>Sex</th>
                    <td><span class="badge badge-light">{{ patient.sex }}</span></td>
                </tr>
                <tr>
                    <th>Job</th>
                    <td><span class="badge badge-light">{{ patient.job }}</span></td>
                </tr>
                <tr>
                    <th>City</th>
                    <td><span class="badge badge-light">{{ patient.city }}</span></td>
                </tr>
                <tr>
                    <th>Province</th>
                    <td><span class="badge badge-light">{{ patient.province }}</span></td>
                </tr>
                <tr>
                    <th>Medical History</th>
                    <td><span class="badge badge-light">{{ patient.medical_history }}</span></td>
                </tr>
                <tr>
                    <th>Education</th>
                    <td><span class="badge badge-light">{{ patient.education }}</span></td>
                </tr>
                <tr>
                    <th>Symptoms</th>
                    <td><span class="badge badge-light">{{ patient.symptoms }}</span></td>
                </tr>
            </tbody>
        </table>
        <a class="btn btn-outline-primary mt-4" href="{% url 'info:patient' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}

info/templates/info/index.html
{% extends 'info/base.html' %}
{% load static %}
{% block title %}Total Cases{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center info my-5 py-4">
                <h1 class="font-weight-bold header">COVID-19 cases in Indonesia</h1>
                <hr>
            </div>
        </div>
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Provinsi</th>
                    <th>Kasus Positif</th>
                    <th>Kasus Sembuh</th>
                    <th>Kasus Meninggal</th>
                </tr>
            </thead>
            <tbody>
                {% for data in semua_data %}
                    <tr>
                        <td>{{ data.provinsi }}</td>
                        <td>{{ data.kasus_positif }}</td>
                        <td>{{ data.kasus_sembuh }}</td>
                        <td>{{ data.kasus_meninggal }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

info/templates/info/rumah_sakit.html
{% extends 'info/base.html' %}
{% load static %}
{% block title %}Hospitals{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 text-center info my-5 py-4">
            <h1 class="font-weight-bold">Special Hospitals for COVID-19 patients</h1>
            <hr>
        </div>
    </div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Province</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Region</th>
            </tr>
        </thead>
        <tbody>
            {% for rumah_sakit in rumah_sakit_rujukan %}
            <tr>
                <td>{{ rumah_sakit.rumah_sakit }}</td>
                <td>{{ rumah_sakit.provinsi }}</td>
                <td>{{ rumah_sakit.alamat }}</td>
                <td>{{ rumah_sakit.nomor_telepon }}</td>
                <td>{{ rumah_sakit.region }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-warning btn-xl my-4" href="{% url 'info:info' %}">Other Info</a>
</div>
{% endblock content %}