TK1_PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('login_register.urls')),
    path('', include('home.urls')),
    path('form/', include('form.urls')),
    path('info/', include('info.urls')),
    path('article/', include('article.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>', views.detail, name="detail"),
    path('tags/<str:name>', views.tags, name="tags"),
    path('register', views.register, name="register"),
    path('register_tags', views.register_tags, name="register_tags"),
]

form/urls.py
from django.urls import path

from . import views
from form.views import UserCreateView

app_name = 'form'

urlpatterns = [
    path('', UserCreateView.as_view(), name='form'),
    path('success/', views.success, name='success'),
]

home/urls.py
from django.urls import path
from . import views

app_name= 'home'

urlpatterns = [
    path('', views.index, name='index')
]

info/urls.py
from django.urls import path
from . import views

app_name= 'info'

urlpatterns = [
    path('', views.index, name='info'),
    path('patient/', views.patient, name='patient'),
    path("details/<int:pk>", views.patient_details, name="patient_details"),
    path("delete/<int:pk>", views.delete_patient, name="delete_patient"),
    path('rumah_sakit/', views.daftar_rumah_sakit, name="daftar_rumah_sakit"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import requests

# Create your views here.
def index(request):
    response = requests.get('https://api.kawalcorona.com/indonesia/')
    data = response.json()
    kasus_indonesia = {}
    kasus_indonesia['positif'] = data[0]['positif']
    kasus_indonesia['sembuh'] = data[0]['sembuh']
    kasus_indonesia['meninggal'] = data[0]['meninggal']
    kasus_indonesia['dirawat'] = data[0]['dirawat']
    return render(request, 'home/index.html', {
        "kasus_indonesia": kasus_indonesia
    })

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Arvo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'home/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'home/images/icons8_virus_48_xbi_icon.ico' %}">
    <title>Form Corona - {% block title %}{% endblock title %}</title>
    <script>
        window.onscroll = () => {
            if (window.innerHeight + window.scrollY >= document.querySelector('#main').offsetHeight) {
                document.querySelector('.navbar').style.background = '#00ac96';
            } else {
                document.querySelector('.navbar').style.background = 'transparent';
            }
        }
    </script>
</head>
<body>

    <!-- Header -->
    {% block header %}
    {% endblock  %}


    <!-- Fill content -->
    {% block content %}
    {% endblock content %}

    
    <!-- Footer -->
    {% include "home/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

        
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/footer.html
{% load static %}
<!--Footer section-->
<footer class="page-footer font-small">
    <div class="footer-copyright text-center py-3">
        ©2020 Kelompok B15, All Rights Reserved
    </div>
</footer>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

<!-- Title -->
{% block title %}Home{% endblock title %}

<!-- Header -->
{% block header %}
{% include 'home/navbar.html' %}
{% endblock  %}

<!-- Content -->
{% block content %}

    <main>
        <div class="container">
            <!-- Info covid -->
            <section id="main">
                <div class="row justify-content-center my-4 py-4">
                    <div class="col-lg-8 text-center info">
                        <h1 class="font-weight-bold">COVID - 19</h1>
                        <hr>
                        <p>
                            Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus
                        </p>
                        <p>
                            Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without
                            requiring special treatment.
                        </p>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="card bg-danger mx-2 mb-3 text-center" style="max-width: 18rem;">
                        <div class="card-header">Coronavirus Cases in Indonesia</div>
                        <div class="card-body">
                            <h5 class="card-title">Positive</h5>
                            <p class="card-text">{{ kasus_indonesia.positif }}</p>
                        </div>
                    </div>
                    <div class="card bg-success mx-2 mb-3 text-center" style="max-width: 18rem;">
                        <div class="card-header">Coronavirus Cases in Indonesia</div>
                        <div class="card-body">
                            <h5 class="card-title">Recover</h5>
                            <p class="card-text">{{ kasus_indonesia.sembuh }}</p>
                        </div>
                    </div>
                    <div class="card bg-light mx-2 mb-3 text-center" style="max-width: 18rem;">
                        <div class="card-header">Coronavirus Cases in Indonesia</div>
                        <div class="card-body">
                            <h5 class="card-title">Death</h5>
                            <p class="card-text">{{ kasus_indonesia.meninggal }}</p>
                        </div>
                    </div>
                    <div class="card bg-warning mx-2 mb-3 text-center" style="max-width: 18rem;">
                        <div class="card-header">Coronavirus Cases in Indonesia</div>
                        <div class="card-body">
                            <h5 class="card-title">Treated</h5>
                            <p class="card-text">{{ kasus_indonesia.dirawat }}</p>
                        </div>
                    </div>
                </div>
            </section>

            <!-- Gambar-gambar -->
            <section>
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h3 class="font-weight-bold">To Prevent the Spread of COVID-19:</h3>
                        <hr>
                        <p>Protect yourself and others around you by knowing the facts and taking appropriate precautions. Follow advice provided
                        by your local health authority.</p>
                    </div>
                </div>
                <div id="images">
                    <div class="container-fluid p-0">
                        <div class="row no-gutters">
                            <div class="col-lg-4 col-sm-6">
                                <a class="images-box">
                                    <img class="img-fluid" src="{% static 'home/images/wash-hand.jpg' %}" alt="" />
                                    <div class="images-box-caption">
                                        <div class="project-category text-white-50">TIPS</div>
                                        <div class="project-name">Clean your hands often</div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-4 col-sm-6">
                                <a class="images-box">
                                    <img class="img-fluid" src="{% static 'home/images/safe-distance.jpg' %}" alt="" />
                                    <div class="images-box-caption">
                                        <div class="project-category text-white-50">TIPS</div>
                                        <div class="project-name">Maintain a safe distance</div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-4 col-sm-6">
                                <a class="images-box">
                                    <img class="img-fluid" src="{% static 'home/images/wear-masker.jpg' %}" alt="" />
                                    <div class="images-box-caption">
                                        <div class="project-category text-white-50">TIPS</div>
                                        <div class="project-name">Wear a mask when physical distancing is not possible</div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-4 col-sm-6">
                                <a class="images-box">
                                    <img class="img-fluid" src="{% static 'home/images/stay-home.jpg' %}" alt="" />
                                    <div class="images-box-caption">
                                        <div class="project-category text-white-50">TIPS</div>
                                        <div class="project-name">Stay home if you feel unwell</div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-4 col-sm-6">
                                <a class="images-box">
                                    <img class="img-fluid" src="{% static 'home/images/cough.jpg' %}" alt="" />
                                    <div class="images-box-caption">
                                        <div class="project-category text-white-50">TIPS</div>
                                        <div class="project-name">Cover your nose and mouth with your bent elbow or a tissue when you cough or sneeze</div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-lg-4 col-sm-6">
                                <a class="images-box">
                                    <img class="img-fluid" src="{% static 'home/images/medical-attention.jpg' %}" alt="" />
                                    <div class="images-box-caption">
                                        <div class="project-category text-white-50">TIPS</div>
                                        <div class="project-name">If you have a fever, cough and difficulty breathing, seek medical attention</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
            </section>
            <section id="about-me">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center info">
                        <h2 class="font-weight-bold">About Us</h2>
                        <hr>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <img class=".img-thumbnail w-50 mx-auto d-block images" src="{% static 'home/images/teamwork.png' %}" alt="team">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 my-3">
                        <p>
                            Corona Form is a website run by a group of Faculty of Computer Science UI students with the
                            goal of making Indonesia COVID-19 statistics available in an accurate and reliable way.
                            Information is extracted right from patients safely and presented transparently. Doctors,
                            researchers, and statisticians are able to extract and implement the data into researches 
                            and future projects. We also provide some articles and recent headlines to keep users
                            up-to-date with COVID-19.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock content %}

home/templates/home/navbar.html
{% load static %}
<!--Header section-->
<header>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top scrolling-navbar">
        <div class="container">
            <!--Navbar brand-->
            <a class="navbar-brand font-weight-bold" href="{% url 'home:index' %}"><img src="https://img.icons8.com/fluent/48/000000/virus.png" />CORONA FORM</a>

            <!--Collapse button if we shrink to smaller screen-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basicExampleNav">

                <!-- Links -->
                <ul class="navbar-nav ml-auto smooth-scroll">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'form:form' %}">Form</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'article:index' %}">Article</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            COVID Info
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'info:info' %}">Total Cases</a>
                            <a class="dropdown-item" href="{% url 'info:patient' %}">Patient Data</a>
                            <a class="dropdown-item" href="{% url 'info:daftar_rumah_sakit' %}">Hospital List</a>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'login' %}">{{user.username}} (Login)</a>
                    </li>
                    {% else %} 
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>