TK1_PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('login_register.urls')),
    path('', include('home.urls')),
    path('form/', include('form.urls')),
    path('info/', include('info.urls')),
    path('article/', include('article.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>', views.detail, name="detail"),
    path('tags/<str:name>', views.tags, name="tags"),
    path('register', views.register, name="register"),
    path('register_tags', views.register_tags, name="register_tags"),
]

form/urls.py
from django.urls import path

from . import views
from form.views import UserCreateView

app_name = 'form'

urlpatterns = [
    path('', UserCreateView.as_view(), name='form'),
    path('success/', views.success, name='success'),
]

article/models.py
from django.db import models
import os

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    text = models.TextField()
    def __str__(self):
        return self.title

class Tags(models.Model):
    name = models.CharField(max_length=100)
    article = models.ForeignKey(
        Article, 
        on_delete=models.CASCADE, 
        related_name='tags'
    )
    def __str__(self):
        return self.name

class Image(models.Model):
    article = models.ForeignKey(
        Article, 
        on_delete=models.CASCADE, 
        related_name='image'
    )
    image = models.ImageField(default=None)

article/forms.py
from django.forms import ModelForm
from .models import Article, Image, Tags


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'author', 'text']

class TagsForm(ModelForm):
    class Meta:
        model = Tags
        fields = ['name', 'article']


class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['image']

article/views.py
from django.http import request
from django.shortcuts import redirect, render
from .models import Article, Tags
from .forms import ArticleForm, TagsForm, ImageForm


def index(request):
    article = Article.objects.all()
    context = {'page_title': 'Article Corona Terbaru', 'article': article}
    return render(request, "article/index.html", context)


def detail(request, id):
    article = Article.objects.get(id=id)
    context = {'page_title': article.title, 'article': article}
    return render(request, "article/detail.html", context)


def tags(request, name):
    tags = Tags.objects.filter(name=name)
    article = map(lambda x: x.article, tags)
    context = {'page_title': name, 'article': article}
    return render(request, "article/tags.html", context)


def register(request):
    form_article = ArticleForm(request.POST or None)
    form_image = ImageForm(request.POST or None)
    if (request.method == 'POST'):
        if(form_article.is_valid()):
            form_article.save()
        if(form_image.is_valid()):
            form_image.save()
        return redirect('article:index')
    context =  {'page_title': 'register', 'form_article': form_article,
                'form_image': form_image}
    return render(request, "article/register.html", context)


def register_tags(request):
    form_tags = TagsForm(request.POST or None)
    if (request.method == 'POST' and form_tags.is_valid()):
        form_tags.save()
        return redirect('article:index')
    context = {'page_title': 'register','form_tags': form_tags}
    return render(request, "article/register_tags.html", context)

article/templates/article/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;600;700&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="{% static 'article/style.css' %}" />
  <title>{{ page_title }}</title>
</head>
<body>
  <!-- Header -->
  {% include "home/navbar.html" %}

  <div class="content">
    {% block content %}
    {% endblock content %}

    <!-- Footer -->
    {% include "home/footer.html" %}
  </div>
</body>
</html>

article/templates/article/detail.html
{% extends 'article/base.html' %}

{% block content  %}

<div class="article">
  <h1>{{ article.title }}</h1>
  <h3>{{ article.author }}</h3>
  <img class="thumbnail" src="{% with article.image.all|first as first %}{{ first.image.url }}{% endwith %}">
  <p>
    {% for i in article.tags.all %}<a href="{% url 'article:tags' name=i.name %}" class="tags">{{ i }}</a> {% endfor %}
  </p>
  <p>{{ article.text }}</p>
  {% for i in article.image.all|slice:'1:' %}
  <img class="thumbnail" src="{{ i.image.url }}">
  {% endfor %}
</div>

{% endblock %}

article/templates/article/index.html
{% extends 'article/base.html' %}

{% block content  %}
<h1>Article Terbaru Corona</h1>
{% if user.is_authenticated %}
<h4><a class="btn-atas" href="{% url 'article:register' %}">Daftarkan Artikelmu</a></h4>
<h4><a class="btn-atas" href="{% url 'article:register_tags' %}">Daftarkan Tags Artikelmu</a></h4>
{% endif %}
{% if article %}
<div class="article">
  {% for i in article %}

  <div class="child">
    <h2>{{ i.title }}</h3>
    <h4>{{ i.author }}</h5>

    <p>
      {% for j in i.tags.all %}<a href="{% url 'article:tags' name=j.name %}" class="tags">{{ j }}</a> {% endfor %}
    </p>

    <img class="thumbnail" src="{% with i.image.all|first as first %}{{ first.image.url }}{% endwith %}">
    <p>{{ i.text|truncatechars:255 }}</p>
    <a href="{% url 'article:detail' id=i.id %}">See more</a>
  </div>
  {% endfor %}
</div>
{% else %}
<h3>Something is wrong. There's no article :(</h3>
{% endif %}
{% endblock  %}

article/templates/article/register.html
{% extends 'article/base.html' %}

{% block content  %}
<h1> Register Article </h1>
<div>
  <form method="POST">
    {% csrf_token %}
    {{ form_article.as_p }}
    {{ form_image.image }}
    <input class="btn" type="submit" value="Submit" />
  </form>
</div>

{% endblock  %}

article/templates/article/register_tags.html
{% extends 'article/base.html' %}

{% block content  %}
<h1> Register Article Tags </h1>
<div>
  <form method="POST">
    {% csrf_token %}
    {{ form_tags.as_p }}
    <input class="btn" type="submit" value="Submit" />
  </form>
</div>

{% endblock  %}

article/templates/article/tags.html
{% extends 'article/base.html' %}

{% block content  %}
<h1>Article Berdasarkan</h1>

{% if article %}
<div class="article">
  {% for i in article %}

  <div class="child">
    <h3>{{ i.title }}</h3>
    <h5>{{ i.author }}</h5>

    <p>
      {% for j in i.tags.all %}<span class="tags">{{ j }}</span> {% endfor %}
    </p>

    <img class="thumbnail" src="{% with i.image.all|first as first %}{{ first.image.url }}{% endwith %}">
    <p>{{ i.text|truncatechars:255 }}</p>
    <a href="{% url 'article:detail' id=i.id %}">See more</a>
  </div>
  {% endfor %}
</div>
{% else %}
<h3>Something is wrong. There's no article :(</h3>
{% endif %}
{% endblock  %}